#!/bin/bash

################################################################
# This program is used to manage basic commands for
# managing a project, such as git.
# Created by: Avery Reed on 2/14/17
# Last Edited by: Avery Reed 2/16/17
################################################################

DIFF=$(diff manage /usr/local/bin/manage)
if [ "$DIFF" != "" ] && [ "$2" != "up" ]; then
  echo "Manage is not upto date!"
  ./manage -s up
  manage -i
  manage $1 $2 $3 $4
  exit
fi

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "push or -p - push everything or specified file"
  echo "test or -t - build and test engine and sample project"
  echo "update or -u - update get branch from main"
  echo "setup or -s - make it so you can run the program without ./, it also works everywhere, also updates it"
  echo "create or -c - create a git branch"
  echo "install or -i - install missing dependicies"
  echo "engine or -e - rebuild engine"
  echo "game or -g - build game based on current engine build"
  echo "clean or -cl - clean out all built files and engine library"
  echo "doc or -dc - generate doc (html and pdf)"
  echo "In the works:"
  echo "reg or -r - CAN: register git info like username, email, and CANNOT YET:(need to add) key"
  echo "conf or -c - reconfigure makefile #in the works"
  echo "debug or -d - compile program and run it in debug mode"
elif [ "$1" == "doc" ] || [ "$1" == "-dc" ]; then
  cd engine
  doxygen dconfig
  cd ../docs/latex/
  make
  cd ../..
elif [ "$1" == "push" ] || [ "$1" == "-p" ]; then
  manage clean
  STAT=$(git status | grep engine)
  if [ "$STAT" != "" ]; then
    manage doc
  fi
  if [ "$2" = "all" ]; then
    git add *
  else
    git add $2
  fi
  echo "What did you change:"
  read change
  git commit -m "$change"
  manage -u
  git config --global push.defualt simple
  git push
elif [ "$1" == "test" ] || [ "$1" == "-t" ]; then
  if [ "$2" = NULL ]; then
    echo "Specify games directory"
  else
    cd engine
    ./build.sh
    cd ..
    cd $2
    ./build.sh
    ./a.out
  fi
elif [ "$1" == "engine" ] || [ "$1" == "-e" ]; then
  cd engine
  ./build.sh
elif [ "$1" == "game" ] || [ "$1" == "-g" ]; then
  if [ "$2" = NULL ]; then
    echo "Specify games directory"
  else
    cd $2
    ./build.sh
  fi
elif [ "$1" == "clean" ] || [ "$1" == "-cl" ]; then
  rm *.o*
  cd engine
  rm *.o*
  rm *.a
  cd ..
  cd testgames
  rm */a.out
  cd ../..
elif [ "$1" == "conf" ] || [ "$1" == "-cf" ]; then
  #NEED TO FINISH THIS
  echo "This is still being worked on"
  #echo "Configuring..."
  #make clean
  #touch .cache/mf
  #echo "################################################################" >> .cache/mf
  #echo "# This makefile is for the temp main file for testing purposes." >> .cache/mf
  #echo "# Created by: Avery Reed on 2/14/17" >> .cache/mf
  #echo "# Last Edited by: Avery Reed `date`" >> .cache/mf
  #echo "################################################################" >> .cache/mf
  #echo "" >> .cache/mf
  #echo "FLAGS = -lSDL2" >> .cache/mf
  #echo "" >> .cache/mf
  #echo "################################################################" >> .cache/mf
  #echo "# Build Game" >> .cache/mf
  #echo "################################################################" >> .cache/mf
elif [ "$1" == "update" ] || [ "$1" == "-u" ]; then
  git status
  git pull
elif [ "$1" == "setup" ] || [ "$1" == "-s" ]; then
  echo "You should only do this from the actual program, (./manage), not from the path."
  echo -n "Are you sure you want to add/update the command 'manage' to your path? (y/n): "
  read ans
  if [ "$ans" == "y" ]; then
    echo "Ok. Adding manage to your path..."
    #export PATH=$PATH:$PWD
    #move to bin
    sudo cp manage /usr/local/bin/
    sudo chmod a+x /usr/local/bin/manage
    echo "Completed. You can now run wihtout ./ and from anywhere."
  fi
elif [ "$1" == "create" ] || [ "$1" == "-c" ]; then
  echo -n "Would you like to clone a branch or make a new branch (c/n): "
  read ans
  if [ "$ans" == "c" ]; then
    echo "Okay. What is the location of the repo to clone:"
    read cl
    git clone $cl
  elif [ "$ans" == "n" ]; then
    echo -n "Is this the current directory? If not name the directory (y/new name): "
    read ans
    if [ "$ans" == "y" ]; then
      echo "Creating $ans branch"
      git init
    else
      echo "Making $ans directory"
      mkdir $ans
      cd $ans
      echo "Creating $ans branch"
      git init
      cd ..
    fi
  else
    echo "Not an option."
  fi
elif [ "$1" == "debug" ] || [ "$1" == "-d" ]; then
  if [ "$2" == NULL ]; then
    echo "No specified file. Please specify with location of exectutable."
  else
    echo "Note: (as of right now) this doesn't not rebuild the program"
    echo "q to quit"
    echo "run to test"
    gdb $2
  fi
elif [ "$1" == "install" ] || [ "$1" == "-i" ]; then
  sudo apt-get install git
  sudo apt-get install g++
  sudo apt-get install gdb
  sudo apt-get install libsdl2-2.0-0
  sudo apt-get install libsdl2-image-2.0-0 libsdl2-image-dbg libsdl2-image-dev
  sudo apt-get install libsdl2-ttf-2.0-0 libsdl2-ttf-dbg libsdl2-ttf-dev
  sudo apt-get install doxygen graphviz
elif [ "$1" == "reg" ] || [ "$1" == "-r" ]; then
  echo -n "User Name: "
  read un
  echo -n "Email: "
  read em
  git config --global user.name "$un"
	git config --global user.email $em
  echo "(key creation coming soon)"
else
  echo "No input value"
  echo "-h or --help for help"
  echo "if you are getting any errors (since I kinda just through this engines manager together last minute) let me know"
  echo "or even better try and fix it yourself (haha)"
  echo "install with manage -s and install dependicies with -i"
fi
