#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "push or -p - push everything"
  echo "test or -t - build and test sample program"
  echo "conf or -c - reconfigure makefile #in the works"
  echo "update or -u - update get branch from main"
elif [ "$1" == "push" ] || [ "$1" == "-p" ]; then
  if [ "$2" != NULL ]; then
    git add $2
  else
    git add *
  fi
  echo "What did you change:"
  read change
  git commit -m "$change"
  git config --global push.defualt simple
  git push
elif [ "$1" == "test" ] || [ "$1" == "-t" ]; then
  make clean
  make
  ./a.out
elif [ "$1" == "conf" ] || [ "$1" == "-c" ]; then
  #NEED TO FINISH THIS
  echo "This is still being worked on"
  #echo "Configuring..."
  #make clean
  #touch .cache/mf
  #echo "################################################################" >> .cache/mf
  #echo "# This makefile is for the temp main file for testing purposes." >> .cache/mf
  #echo "# Created by: Avery Reed on 2/14/17" >> .cache/mf
  #echo "# Last Edited by: Avery Reed `date`" >> .cache/mf
  #echo "################################################################" >> .cache/mf
  #echo "" >> .cache/mf
  #echo "FLAGS = -lSDL2" >> .cache/mf
  #echo "" >> .cache/mf
  #echo "################################################################" >> .cache/mf
  #echo "# Build Game" >> .cache/mf
  #echo "################################################################" >> .cache/mf
elif [ "$1" == "update" ] || [ "$1" == "-u" ]; then
  git status
  git pull
else
  echo "No input value"
fi
